import streamlit as st

def show_guide():
    st.title("📘 Strategy Guide – Signal Confidence Strength")
    st.markdown("""
    This section explains how to interpret the **confidence score** and resulting labels generated by the trading signal model.

    ### 🔍 How Confidence Works:
    - The model outputs a probability that a candle is a **BUY signal**.
    - We translate this into **labels** for human-friendly interpretation.

    ---

    ### 🧠 Confidence Strength Breakdown

    | Confidence %       | Label              | Meaning                                  |
    |--------------------|--------------------|------------------------------------------|
    | **90–100%**        | 🔥 Strong BUY      | Very high conviction — ideal entry zone. |
    | **70–89.99%**      | ✅ Moderate BUY    | Good signal, with decent model backing.  |
    | **50–69.99%**      | ⚠️ Weak BUY        | Slight positive bias — wait for confirmation. |
    | **30–49.99%**      | ⚠️ Weak SELL       | Slight negative bias — stay cautious.    |
    | **10–29.99%**      | ❌ Moderate SELL   | Selling pressure likely — avoid buying.  |
    | **0–9.99%**        | 💀 Strong SELL     | Very bearish — exit or short if applicable. |

    ---

    ### 💡 Tips:
    - Combine this with technical indicators (RSI, MACD) for better decisions.
    - Use **Strong BUY** or **Strong SELL** as clear entry/exit zones.
    - For **Weak signals**, observe next candles or add filters.

    ---
    """)
